---

- name: Playbook demonstrates the functionality of loop while creaiing users 
  hosts: slaves
  vars:
    myusers:
      - rajesh
      - venkat
      - mansoor
 
  tasks:
    - name: The task creates 3 users while it loops
      user: 
        name: "{{ item }}"
        state: absent
      loop: "{{ myusers }}"  
