---

- name: Playbook demonstrates the functionality of loop while creaiing users 
  hosts: webserver
 
  tasks:
    - name: The task creates 3 users while it loops
      user: 
        name: "{{ item }}"
        state: present
      loop: "{{ webusers }}"  
